### ISSUE TITLE
Rename this repo to remove "model"!

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/variant-representation#3]
The vmc github repo is established and has an independent purpose that falls under the umbrella of the Var Rep subgroup within the GA4GH GKS workstream.  Initially this repo was to establish a repo for capturing all Var Rep subgroup concerns and developments. 

There was some initial discussion of bringing the existing VMC repo under this github repo, but it is clearly separate. 

To avoid confusion with "where's the spec?" "where's the model?" "where to i put an issue for the appropriate group?" the suggestion was made to remove the "-model" suffix from this repo so that it did not get confused with the VMC model project and add some content to the README of this project to clarify, link and instruct folks on when/where to add info to the specific repos.

**Comment by mbaudis** [comment]
Changed the name to remove model.
